# Global settings
global:
  installGatewayV2Crd: ${installGatewayV2Crd}
  # Kubernetes provider (options: "oke", "gke", "eks", "aks", "aro")
  provider: "${k8s_provider}"
  # AWS region (applicable for EKS provider)
  awsRegion: "${awsRegion}"
# Namespace configurations
namespaces:
  nullplatformTools: "${nullplatformTools}"
  gateway: "${gateway_namespace}"
ingressControllers:
  public:
    name: "${ingress_public_name}"
    enabled: ${ingress_public_enabled}
    scope: ${ingress_public_scope}
    domain: "${ingress_public_domain}"
  private:
    name: "${ingress_private_name}"
    enabled: ${ingress_private_enabled}
    scope: ${ingress_private_scope}
    domain: "${ingress_private_domain}"
# Gateway configurations
gateway:
  useClusterIP: ${gateway_use_cluster_ip}
  http:
    enabled: ${gateway_enabled}
  internal:
    enabled: ${gateway_internal_enabled}
    name: "gateway-private"
    aws:
      name: ${gateway_internal_aws_name}
      securityGroups: "${gateway_private_aws_security_groups}"
      dns_name: ${gateway_private_aws_dns_name}
    azure:
      networkSecurityGroup: "${gateway_private_azure_nsg}"
    gcp:
      firewallRule: "${gateway_private_gcp_firewall}"
    oci:
      securityListManagementMode: "${gateway_private_oci_security_list_management_mode}"
    azure_load_balancer_subnet: ${gateway_internal_azure_load_balancer_subnet}
    loadBalancerSourceRanges: []
    addresses: {}
    autoscaling:
      minReplicas: 2
      maxReplicas: 10
    loadBalancerType: "internal"  # internal, external
  public:
    name: "gateway-public"
    enabled: ${gateway_public_enabled}
    aws:
      name: ${gateway_public_aws_name}
      securityGroups: "${gateway_public_aws_security_groups}"
      dns_name: ${gateway_public_aws_dns_name}
    azure:
      networkSecurityGroup: "${gateway_public_azure_nsg}"
    gcp:
      firewallRule: "${gateway_public_gcp_firewall}"
    oci:
      securityListManagementMode: "${gateway_public_oci_security_list_management_mode}"
    loadBalancerSourceRanges: []
    addresses: {}
    autoscaling:
      minReplicas: 2
      maxReplicas: 10
    loadBalancerType: "external"  # internal, external
# Gateway API configuration
gateways:
  enabled: ${gateways_enabled}
gatewayAPI:
  enabled: ${gatewayapi_enabled}
  crds:
    install: ${gatewayapi_crds_install}
tls:
  required: ${tls_required}
  secretName: "${tls_secret_name}"
  secretPrivateName: "${tls_secret_private_name}"
