# Global settings
global:
  installGatewayV2Crd: ${installGatewayV2Crd}
  # Kubernetes provider (options: "oke", "gke", "eks", "aks", "aro")
  provider: "${k8s_provider}"
  # AWS region (applicable for EKS provider)
  awsRegion: "${awsRegion}"
# Namespace configurations
namespaces:
  # Namespace for Null platform resources
  nullplatformApplications: "nullplatform"
  nullplatformTools: "nullplatform-tools"
  gateway: "gateways"
ingressControllers:
  public:
    name: "${ingress_public_name}"
    enabled: ${ingress_public_enabled}
    scope: ${ingress_public_scope}
    domain: "${ingress_public_domain}"
  private:
    name: "${ingress_private_name}"
    enabled: ${ingress_private_enabled}
    scope: ${ingress_private_scope}
    domain: "${ingress_private_domain}"
# TLS configuration
tls:
  required: ${tls_required}
  # Name of the TLS secret
  secretName: "wildcard-tls"
  # Gateway configurations
gateway:
  useClusterIP: ${gateway_use_cluster_ip}
  http:
    enabled: ${gateway_enabled}
  internal:
    enabled: ${gateway_internal_enabled}
    name: "gateway-private"
    aws:
      name: ${gateway_internal_aws_name}
      securityGroups: "${gateway_private_aws_security_groups}"
      dns_name: ${gateway_private_aws_dns_name}
    azure:
      networkSecurityGroup: "${gateway_private_azure_nsg}"
    gcp:
      firewallRule: "${gateway_private_gcp_firewall}"
    oci:
      securityListManagementMode: "${gateway_private_oci_security_list_management_mode}"
      subnet: "${gateway_private_oci_subnet}"
    azure_load_balancer_subnet: ${gateway_internal_azure_load_balancer_subnet}
    loadBalancerSourceRanges: []
    addresses: {}
    autoscaling:
      minReplicas: 2
      maxReplicas: 10
    loadBalancerType: "internal"  # internal, external
  public:
    name: "${gateway_public_name}"
    enabled: ${gateway_public_enabled}
    aws:
      name: ${gateway_public_aws_name}
      securityGroups: "${gateway_public_aws_security_groups}"
      dns_name: ${gateway_public_aws_dns_name}
    azure:
      networkSecurityGroup: "${gateway_public_azure_nsg}"
      subnet: "${gateway_public_azure_load_balancer_subnet}"
    gcp:
      firewallRule: "${gateway_public_gcp_firewall}"
    oci:
      securityListManagementMode: "${gateway_public_oci_security_list_management_mode}"
      subnet: "${gateway_public_oci_subnet}"
    loadBalancerSourceRanges: []
    addresses: {}
    autoscaling:
      minReplicas: 2
      maxReplicas: 10
    loadBalancerType: "${gateway_public_load_balancer_type}"
    %{ if length(gateway_public_extra_listeners) > 0 }
    extraListeners:
    %{ for l in gateway_public_extra_listeners }
      - name: ${l.name}
        hostname: "${l.hostname}"
        secretName: ${l.secretName}
    %{ endfor }
    %{ else }
    extraListeners: []
    %{ endif }
# Nullplatform configurations
nullplatform:
  apiKey: "${np_api_key}"
  secretName: "" #If provided will mount it from an existing secret
# Logging configurations
controlPlane:
  enabled: ${controlPlane_enabled}
  agent:
    image: "public.ecr.aws/nullplatform/controlplane-agent:latest"
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 150Mi
logging:
  enabled: ${logging_enabled}
  applicationLogs:
    enabled: ${logging_application_logs_enabled}
  mountDockerContainers: ${logging_mount_docker_containers}
  controller:
    image: "public.ecr.aws/nullplatform/k8s-logs-controller:latest"
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 700m
        memory: 300Mi
  prometheus:
    enabled: ${prometheus_enabled}
    exporterPort: ${exporter_prometheus_port}
  gelf:
    enabled: ${gelf_enabled}
    host: "${gelf_host}"
    port: ${gelf_port}
  loki:
    enabled: ${loki_enabled}
    host: "${loki_host}"
    port: ${loki_port}
    user: "${loki_user}"
    password: "${loki_password}"
    bearerToken: "${loki_bearerToken}"
    matchRegex: "container.*.application"
  dynatrace:
    enabled: ${dynatrace_enabled}
    logsEnabled: ${dynatrace_logs_enabled}
    metricsEnabled: ${dynatrace_metrics_enabled}
    apiKey: "${dynatrace_apiKey}"
    environmentId: "${dynatrace_environmentid}"
  datadog:
    enabled: ${datadog_enabled}
    logsEnabled: ${datadog_logs_enabled}
    metricsEnabled: ${datadog_metrics_enabled}
    apiKey: "${datadog_apiKey}"
    region: "${datadog_region}"
  newrelic:
    enabled: ${newrelic_enabled}
    logsEnabled: ${newrelic_logs_enabled}
    metricsEnabled: ${newrelic_metrics_enabled}
    licenseKey: "${newrelic_licenseKey}"
    region: "${newrelic_region}"
# CloudWatch configuration
cloudwatch:
  enabled: ${cloudwatch_enabled}
  region: "${awsRegion}"
  retentionDays: 7
  logs:
    enabled: ${cloudwatch_logs_enabled}
  performanceMetrics:
    enabled: ${cloudwatch_performancemetrics_enabled}
  customMetrics:
    enabled: ${cloudwatch_custommetrics_enabled}
  accessLogs:
    enabled: ${cloudwatch_accesslogs_enabled}
# Metrics server configuration
metricsServer:
  enabled: ${metricsserver_enabled}
# Gateway API configuration
gateways:
  enabled: ${gateways_enabled}
gatewayAPI:
  enabled: ${gatewayapi_enabled}
  crds:
    install: ${gatewayapi_crds_install}
# Image pull secret configuration
imagePullSecrets:
  enabled: ${imagePullSecrets_enabled}
  name: image-pull-secret-nullplatform
  registry: "${imagePullSecrets_registry}"
  username: "${imagePullSecrets_username}"
  password: "${imagePullSecrets_password}"
